; ok, an ini file
; todo: title to move into datbase 
title = "web-app example site"
; magic_number for registering new logins, tell those who need logins 
magic_number = 23432
timezone = "Europe/Oslo"

; list all admins for automatic admin elevation
admin[] = "me@localhost"
admin[] = "other@localhost"

; database details 
[database]
server = "192.168.1.3"
database = "example-site"
user = "ex-site-user"
password = "RNq7nbOh_lwFnrgy"
prefix = "ex_s"

